language: go

# Disable git shallow clone. We need full history for validating copyright year of each file.
git:
    depth: false

# Golang version matrix
go:
    - 1.11

install:
    # Get tools used in Makefile
    - make get-tools

addons:
  apt:
    packages: mtools liblzma-dev

before_script:
    # Print build info.
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_REPO_SLUG

    # Rename the branch we're on, so that it's not in the way for the
    # subsequent fetch. It's ok if this fails, it just means we're not on any
    # branch.
    - git branch -m temp-branch || true
    # Git trick: Fetch directly into our local branches instead of remote
    # branches.
    - git fetch origin 'refs/heads/*:refs/heads/*'
    # Get last remaining tags, if any.
    - git fetch --tags origin

jobs:
  include:
    - stage: build
      os: linux
      script:
          - make build
          - make extracheck
    - stage: build
      os: osx
      script: make build
    - stage: test
      os: osx
      install: make install
      script: cd ./tests-acceptance-mac/ && ./test-mac.sh
    - stage: test
      os: linux
      script:
          - make coverage
          - make test

after_success:
    # Integrate with https://codecov.io
    - bash <(curl -s https://codecov.io/bash)
